apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-app1
spec:
  schedule: "0 7 * * *" # scale up app1 at 7am UTC
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              args:
                - scale
                - deployment
                - app1
                - --replicas=20
          serviceAccountName: default