---
apiVersion: v1
kind: Service
metadata:
  name: service-app1
spec:
  selector:
    app: app
    version: app1
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-app2
spec:
  selector:
    app: app
    version: app2
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-apps
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000